on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "testing git hup action"
        run: pwd

      -name: "printing"
       run: echo sharif 

        
